CREATE TABLE IF NOT EXISTS USER
(
	ID INT ,  
	ENABLED CHAR(5), 
	EMAIL CHAR(30), 
	USERNAME CHAR(10), 
	PASSWORD CHAR(10)
);
INSERT INTO USER(ID, ENABLED, EMAIL, USERNAME, PASSWORD) VALUES (1, 'TRUE', 'asha_rajan@homedepot.com', 'asha','project');

CREATE TABLE IF NOT EXISTS AUTHORITIES
(
	USERNAME CHAR(10), 
	AUTHORITY CHAR(10)
);

INSERT INTO AUTHORITIES(USERNAME, AUTHORITY) VALUES ('asha','Y');

CREATE TABLE IF NOT EXISTS category
(
	ID INT , 
	NAME CHAR(30),
	SLUG CHAR(30),
	PARENT_ID INT,
	MODULE_ID INT,
	DELETELOCK INT
);

CREATE TABLE IF NOT EXISTS module
(
	ID INT , 
	NAME CHAR(30),
	TITLE CHAR(30),
	STATUS INT,
	createdAt DATE
);

CREATE TABLE IF NOT EXISTS comment
(
	ID INT , 
	CONTENT CHAR(30),
	STATUS INT,
	createdAt DATE,
	itemType CHAR(30),
	ITEMID INT
);

CREATE TABLE IF NOT EXISTS content
(
	ID INT , 
	SLUG CHAR(30),
	TITLE CHAR(30),
	STATUS INT,
	createdAt DATE,
	CONTENT CHAR(2086), 
	FILENAME CHAR(30)
);


CREATE TABLE IF NOT EXISTS slideshowitem
(
	ID INT , 
	TITLE CHAR(30),
	FILENAME CHAR(30),
	ORDERING INT
);

CREATE TABLE IF NOT EXISTS slideshow
(
	ID INT , 
	TITLE CHAR(30),
);

CREATE TABLE IF NOT EXISTS page
(
	ID INT , 
	SLUG CHAR(30),
	TITLE CHAR(30),
	CONTENT CHAR(2086)
);



